### ISSUE TITLE
White extention window on Opera GX

### ISSUE THREAD

**Issue by ClayMix-the-creator** [one-zero-eight/browser-extension#2] opened 2024-11-07 13:46 UTC
### Describe the bug

Opera GX core:114.0.5282.159
One day the extention window became white. Moving the cursor at the icons at top makes them visible as they change colors. Also visible buttons of autologin and course sync
Downloaded via Chrome extention page as Opera able to apply extentions to it. Extention reinstall doesn't help

### Reproduction

1. Download Opera GX
2. Go to InnoHassle website
3. Go to "Extentions" page
4. Install InnoHassle extention via Google Chrome link
5. Open the "InnoHassle" extention

### Screenshots / Additional context

![image](https://github.com/user-attachments/assets/230d8a06-d96a-4ebd-8593-da492082e7fd)
Video available on Google Drive: https://drive.google.com/file/d/1Dq8luiQsU8fHNclc9HIHSdFdb3kqpmZ1/view?usp=sharing

**Comment by ArtemSBulgakov** [comment] 2024-11-07 13:55
Hi. Thanks for the issue! I've transferred it to appropriate repository.

Seems like Opera handles background color of the root element differently. We'll fix it this week.

**Comment by ArtemSBulgakov** [comment] 2024-11-13 13:51
@ClayMix-the-creator The extension is now [updated in Chrome Web Store](https://chromewebstore.google.com/detail/innohassle-tools/cbeffcchbpgcmaphbpnnnjbaighmobmn). Could you please check whether the issue is fixed?

**Comment by ClayMix-the-creator** [comment] 2024-11-13 15:44
@ArtemSBulgakov It seems to be alright. Thanks!
![изображение_2024-11-13_184413716](https://github.com/user-attachments/assets/5ecfef97-02dd-489d-95aa-bebf1c4e82c9)

**Closed** 2024-11-13 15:44 UTC
Labels: bug
